// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zycuzckmgivqsmxumqut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Y3V6Y2ttZ2l2cXNteHVtcXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MzgzMTEsImV4cCI6MjA0OTUxNDMxMX0.9v2ZGDBmdgYA2YDKeQSIim83b8MRdJ_ZOt1C5W3hCD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);